### ISSUE TITLE
Don't show 'Link' menu entry in 'Cast media' submenu.

### ISSUE THREAD

**Issue by simonbcn** [Rafostar/cast-to-tv-links-addon#1]
```
Arch Linux
GNOME Shell 3.32.2
gnome-shell-extension-cast-to-tv v9 (installed from https://extensions.gnome.org/extension/1544/cast-to-tv)
cast-to-tv-links-addon git version (installed today)
```
I have installed the addon and npm modules:
![captura_20190831_150459](https://user-images.githubusercontent.com/428231/64064438-b548ee00-cc01-11e9-9a58-d3014d2d9c5e.png)
![captura_20190831_150519](https://user-images.githubusercontent.com/428231/64064446-be39bf80-cc01-11e9-89da-294068d43779.png)

I've restarted the PC but it doesn't show the `Link` menu entry in `Cast media` submenu.
![captura_20190831_150754](https://user-images.githubusercontent.com/428231/64064457-ea554080-cc01-11e9-88f5-79cbc1b746be.png)

**Comment by Rafostar** [comment]
This might be a dumb question, but did you enable links-addon in `gnome-tweaks`?

**Comment by simonbcn** [comment]
ok, it was that. I thought when it was installed as an addon of an extension it would automatically activated.

**Comment by Rafostar** [comment]
No prob. It was made as a normal extension, because when I finish it I will try uploading it to Gnome Extensions website. Please note that this is work in progress and I am aware that it does not work on all videos yet.

**Comment by sumandipanshu** [comment]
I'm still not able to get "Link" menu in "Cast Media".
```
Debian 10 (Buster)
GNOME Shell 3.30.2
```
All installations are from source code.

@Rafostar

**Comment by Rafostar** [comment]
@sumandipanshu

> ```
> Debian 10 (Buster)
> GNOME Shell 3.30.2
> ```
> 
> All installations are from source code.

That is probably because your GNOME Shell is too old for a version from source code. GNOME Shell does not have any code stability at all. Each time a new version comes I need to adapt with the changes (thus breaking compatibility with older versions).

If you install from gnome extensions website, it should give you an older version that works on your system.

**Comment by sumandipanshu** [comment]
> @sumandipanshu
> 
> > ```
> > Debian 10 (Buster)
> > GNOME Shell 3.30.2
> > ```
> > 
> > 
> > All installations are from source code.
> 
> That is probably because your GNOME Shell is too old for a version from source code. GNOME Shell does not have any code stability at all. Each time a new version comes I need to adapt with the changes (thus breaking compatibility with older versions).
> 
> If you install from gnome extensions website, it should give you an older version that works on your system.

I tried reinstalling both "Cast to TV" and "Cast to TV - Links Add-on" from gnome extensions website, still I'm not able to get "Link" in menu entry.

**Comment by sumandipanshu** [comment]
> If you install from gnome extensions website, it should give you an older version that works on your system.

@Rafostar Thanks for the help! It worked. :heart:
